language: node_js
sudo: false
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-nikita' ]; then cd .. && eval "mv $currentfolder generator-nikita" && cd generator-nikita; fi
before_deploy:
  - npm install json
  - node_modules/.bin/json -E "this.version='$TRAVIS_TAG'" -f package.json -I
env:
  - CXX=g++-4.8
matrix:
  include:
    - node_js: '4.0.0'
    - node_js: '4.8.4'
    - node_js: '5.12.0'
    - node_js: '6.11.1'
    - node_js: '7.10.1'
    - node_js: '8.1.4'
    - node_js: '8.1.4'
      env: TEMPLATE=web-app
    - node_js: '8.1.4'
      env: TEMPLATE=symfony
    - node_js: '8.1.4'
      env: TEMPLATE=spring-boot
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: npm
  email: JanS@DracoBlue.de
  api_key:
    secure: UqlkX1JFSs224a/dSHWdnIfUARg4onn2C5nk76KWqTJu9un4ewcVZez7uEYUPyYMU9VQigqaakm2SP5/dfAY1wbI2aUT7Ry/co0LHaLLwLmEjzZLo1jI6q9imZz/SPuswEJi1UTipdb9W5TLaGxIkcxidiCCrHlsHsyjx31Kxg4=
  on:
    tags: true
    repo: nikita-kit/generator-nikita
    all_branches: true
    node: 4.2.4
